services:
  - type: web
    name: human-detection-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
